name: secure-container-ci

on:
  push:
    branches: [ "main" ]

jobs:
  secure-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker build -t myapp:latest .

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | \
          sh -s -- -b /usr/local/bin

      - name: Generate SBOM
        run: |
          syft myapp:latest -o json > sbom.json

      
      - name: Scan vulnerabilities
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          image-ref: myapp:latest
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          TAG=${GITHUB_SHA::7}
          docker tag myapp:latest ${{ secrets.DOCKERHUB_USERNAME }}/myapp:$TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:$TAG

      
      
